name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso: checkout (Requisito del profesor)
    - uses: actions/checkout@v4

    # Paso: setup-java (Requisito del profesor)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Paso: build y test (Requisito del profesor)
    - name: Build and Test with Maven
      run: mvn -B package
