name: Release pipeline

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0  

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

          # NUEVO PASO: Otorgar permisos de ejecución al wrapper de Maven
      - name: Dar permisos de ejecucion a mvnw
        run: chmod +x mvnw

      # FASE 5: Control de calidad (Obligatorio)
      - name: Ejecutar Tests y Análisis de SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw verify sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=proria1999 \
            -Dsonar.projectKey=proria1999_mgcss-track-L2-G1 \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.branch.name=main

      # FASE 3: Compilar y empaquetar
      - name: Build
        run: ./mvnw clean package -DskipTests

      # FASE 3: Renombrar el artefacto
      - name: Rename artifact
        run: |
          cp target/*.jar target/app-${{ github.ref_name }}.jar

      # FASE 3: Construir la imagen Docker (Obligatorio)
      - name: Construir Imagen Docker
        run: |
          docker build -t mgcss-track:${{ github.ref_name }} .

      # FASE 3: Publicar la Release con el SHA 
      - name: Create release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: target/app-${{ github.ref_name }}.jar
          generate_release_notes: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
