name: CD Release Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Hacer checkout usando el SHA estable de v4.2.2
      - name: Checkout del código
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 

      # 2. Configurar el entorno de Java usando el SHA estable de v4.4.0
      - name: Configurar JDK 17
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa1989b52a90d1708d3 # v4.4.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # FASE 5: Control de calidad antes de la release (Quality Gate)
      - name: Ejecutar Tests y Análisis de SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw verify sonar:sonar -Dsonar.qualitygate.wait=true

      # FASE 3: Compilar el proyecto y generar el artefacto .jar ejecutable
      - name: Generar artefacto ejecutable (.jar)
        run: ./mvnw package -DskipTests

      # FASE 3: Construir la imagen Docker utilizando el tag como versión
      - name: Construir Imagen Docker
        run: |
          docker build -t mgcss-track:${{ github.ref_name }} .

      # FASE 3: Publicar la Release en GitHub usando el SHA proporcionado por el profesor
      - name: Publicar Release en GitHub
        uses: softprops/action-gh-release@7930ab8db36867eb254ced5b3e42e345d011432e # SHA seguro de v2
        with:
          files: target/*.jar 
          generate_release_notes: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
